name: Build NodeJS app
 
on:
  push:
    branches:
        - main

jobs: 
    test:
        runs-on: ubuntu-latest
        steps:
          - name: Clonando repo de github
            uses: actions/checkout@v5

          - name: Corriendo pruebas
            run: npm run test