name: Build NodeJS app
 
on:
  push:
    branches:
        - main

jobs: 
    test:
        runs-on: ubuntu-latest
        steps:
          - name: Clonando repo de github
            uses: actions/checkout@v5

          - name: Configurando Node.js
            uses: actions/setup-node@v4
            with:
              node-version: '20'

          - name: Instalando dependencias
            run: npm ci

          - name: Corriendo pruebas
            run: npm run test